import NavBar from "@/components/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";

const vazir = Vazirmatn({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="fa_IR">
      <body className={vazir.className}>
        <nav className="lg:px-16 px-4 py-6 max-sm:px-1 ">
          <NavBar />
        </nav>
        <main className="lg:px-16 px-4" dir="rtl">
          {children}
        </main>
      </body>
    </html>
  );
}
